// Generated by tools/generate_grade3_rule_tutor.py. Do not edit.
package com.example.educloud.content

internal object GeneratedGrade3RuleTutor {
    const val VERSION = "grade3-rule-based-demo-0.4"
    const val LABEL = "Grade 3 Maths tutor"
    val cards: List<Grade3RuleTutorCard> = listOf(
        Grade3RuleTutorCard(
            lesson = ContentLesson(
                id = "g3-t1-w1-l1-position", topic = "Positions in order",
                keywords = setOf("position", "order", "first", "second", "third", "fourth", "fifth", "mary", "john"),
                source = "Term 1 · Week 1 · Lesson 1 · Book p.2", version = VERSION,
                passage = "Position tells where someone is in an order. Count from first.", teachingSteps = listOf("Start at the first person.", "Count each position in order.", "Name the position you reach."),
                definition = "A position tells the order of someone or something in a line.", verifiedAnswer = "fifth",
                verifiedAnswerExplanation = "Counting from the first person, Mary is fifth.", answerRules = listOf(LessonAnswerRule(setOf("mary"), "fifth", "Counting from the first person, Mary is fifth.")),
                practicePrompt = "In the same line, what position is Mary?",
            ),
            hint = "Start at the first person and count one place at a time.", question = "What position is Mary in the line?",
            options = listOf("1. Third", "2. Fourth", "3. Fifth"), correctOption = "3",
            correction = "Mary is fifth.",
        ),
        Grade3RuleTutorCard(
            lesson = ContentLesson(
                id = "g3-t1-w2-l1-counting-twos", topic = "Counting in twos",
                keywords = setOf("count", "counting", "twos", "two", "next", "sequence", "302", "304", "306", "511", "513", "515", "517", "519", "610", "612", "614"),
                source = "Term 1 · Week 2 · Lesson 1 · Book p.14", version = VERSION,
                passage = "Counting in twos means adding two each time.", teachingSteps = listOf("Find the change between two numbers.", "Add two for each next number.", "Check that every jump is two."),
                definition = "Counting in twos changes a number by two each time.", verifiedAnswer = "517, 519",
                verifiedAnswerExplanation = "Add two after 515, then add two again.", answerRules = listOf(LessonAnswerRule(setOf("511", "513", "515"), "517, 519", "Add two after 515, then add two again.")),
                practicePrompt = "Continue 610, 612, 614, __, __.",
            ),
            hint = "Find the change, then add two again.", question = "610, 612, 614, __, __",
            options = listOf("1. 616, 618", "2. 615, 616", "3. 618, 620"), correctOption = "1",
            correction = "After 614 come 616 and 618.",
        ),
        Grade3RuleTutorCard(
            lesson = ContentLesson(
                id = "g3-t1-w2-l2-tens-ones", topic = "Tens and ones",
                keywords = setOf("tens", "ones", "place value", "36", "number"),
                source = "Term 1 · Week 2 · Lesson 2 · Book p.16", version = VERSION,
                passage = "A two-digit number has tens and ones. 36 is 3 tens and 6 ones.", teachingSteps = listOf("Look at the tens digit.", "Say how many tens it shows.", "Look at the ones digit and say how many ones it shows."),
                definition = "Tens are groups of ten, and ones are single units.", verifiedAnswer = "3 tens and 6 ones",
                verifiedAnswerExplanation = "In 36, 3 is the tens digit and 6 is the ones digit.", answerRules = listOf(LessonAnswerRule(setOf("36"), "3 tens and 6 ones", "In 36, 3 is the tens digit and 6 is the ones digit.")),
                practicePrompt = "How many tens and ones are in 36?",
            ),
            hint = "The left digit shows tens. The right digit shows ones.", question = "How many tens and ones are in 36?",
            options = listOf("1. 6 tens, 3 ones", "2. 3 tens, 6 ones", "3. 36 tens"), correctOption = "2",
            correction = "36 is 3 tens and 6 ones.",
        ),
        Grade3RuleTutorCard(
            lesson = ContentLesson(
                id = "g3-t1-w2-l4-number-words", topic = "Number words",
                keywords = setOf("number", "words", "write", "twenty", "five", "25"),
                source = "Term 1 · Week 2 · Lesson 4 · Book p.18", version = VERSION,
                passage = "Numbers can be written using words. 25 is twenty five.", teachingSteps = listOf("Read the number.", "Say its number name.", "Write the number name in words."),
                definition = "A number name writes a number using words.", verifiedAnswer = "twenty five",
                verifiedAnswerExplanation = "25 is written in words as twenty five.", answerRules = listOf(LessonAnswerRule(setOf("25"), "twenty five", "25 is written in words as twenty five.")),
                practicePrompt = "Write 25 in words.",
            ),
            hint = "Say the number, then write the words you hear.", question = "How is 25 written in words?",
            options = listOf("1. Twenty five", "2. Fifty two", "3. Two five"), correctOption = "1",
            correction = "25 is written as twenty five.",
        ),
    )
}
