"""Generate Android's offline Grade 3 rule-tutor cards from the USSD JSON pack."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACK_PATH = ROOT / "content" / "grade3_rule_tutor_v1.json"
TARGET = ROOT / "android-app" / "app" / "src" / "main" / "java" / "com" / "example" / "educloud" / "content" / "GeneratedGrade3RuleTutor.kt"


def kotlin(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def values(rows: list[str]) -> str:
    return "listOf(" + ", ".join(kotlin(row) for row in rows) + ")"


def render() -> str:
    payload = json.loads(PACK_PATH.read_text(encoding="utf-8"))
    required_pack = {"schema_version", "pack_id", "content_version", "label", "lessons"}
    if payload.get("schema_version") != "1" or not required_pack <= payload.keys():
        raise RuntimeError("Unsupported Grade 3 rule-tutor schema")
    lessons = payload["lessons"]
    required_lesson = {"id", "topic", "source", "explanation", "definition", "teaching_steps", "matching_terms", "practice_prompt", "hint", "question", "options", "correct_option", "correction", "answer_rules"}
    if not lessons or any(not required_lesson <= row.keys() for row in lessons):
        raise RuntimeError("Each Grade 3 rule-tutor card must include Android and USSD fields")
    if len({row["id"] for row in lessons}) != len(lessons):
        raise RuntimeError("Grade 3 rule-tutor card IDs must be unique")
    if any(len(row["options"]) != 3 or row["correct_option"] not in {"1", "2", "3"} for row in lessons):
        raise RuntimeError("Each card needs three options and a valid correct option")

    rows = [
        "// Generated by tools/generate_grade3_rule_tutor.py. Do not edit.",
        "package com.example.educloud.content",
        "",
        "internal object GeneratedGrade3RuleTutor {",
        f"    const val VERSION = {kotlin(payload['content_version'])}",
        f"    const val LABEL = {kotlin(payload['label'])}",
        "    val cards: List<Grade3RuleTutorCard> = listOf(",
    ]
    for lesson in lessons:
        primary_rule = lesson["answer_rules"][0]
        rules = ", ".join(
            "LessonAnswerRule(setOf(" + ", ".join(kotlin(term) for term in rule["evidence_terms"]) + "), " + kotlin(rule["answer"]) + ", " + kotlin(rule["explanation"]) + ")"
            for rule in lesson["answer_rules"]
        )
        rows.extend([
            "        Grade3RuleTutorCard(",
            "            lesson = ContentLesson(",
            f"                id = {kotlin(lesson['id'])}, topic = {kotlin(lesson['topic'])},",
            f"                keywords = setOf({', '.join(kotlin(term) for term in lesson['matching_terms'])}),",
            f"                source = {kotlin(lesson['source'])}, version = VERSION,",
            f"                passage = {kotlin(lesson['explanation'])}, teachingSteps = {values(lesson['teaching_steps'])},",
            f"                definition = {kotlin(lesson['definition'])}, verifiedAnswer = {kotlin(primary_rule['answer'])},",
            f"                verifiedAnswerExplanation = {kotlin(primary_rule['explanation'])}, answerRules = listOf({rules}),",
            f"                practicePrompt = {kotlin(lesson['practice_prompt'])},",
            "            ),",
            f"            hint = {kotlin(lesson['hint'])}, question = {kotlin(lesson['question'])},",
            f"            options = {values(lesson['options'])}, correctOption = {kotlin(lesson['correct_option'])},",
            f"            correction = {kotlin(lesson['correction'])},",
            "        ),",
        ])
    rows.extend(["    )", "}", ""])
    return "\n".join(rows)


if __name__ == "__main__":
    TARGET.write_text(render(), encoding="utf-8")
    print(f"Wrote {TARGET}")
